easy_admin:
    site_name: 'Election Comores 2019'
    design:
        brand_color: '#3B5998'
        assets:
            js: ['/js/election.js']
    formats:
        date:     'd/m/Y'
        datetime: 'd/m/Y H:i:s'
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - {name: 'delete', icon: 'close'}
    entities:
        Candidat:
            class: App\Entity\Candidat
            form:
                fields:
                    - 'nom'
                    - 'prenom'
                    - {property: 'date_naissance', type: 'birthday', type_options: { widget: 'single_text', 'attr': {'class': 'datepicker'}}}
                    - {property: 'site_web', typ: 'url'}
                    - {property: 'imageFile', type: 'file'}
                    - 'election'
            list:
                fields: ['id', 'postulant', 'age', 'site_web', 'image']
        Electeur:
            class: App\Entity\Electeur
            form:
                fields:
                - 'nom'
                - 'prenom'
                - {property: 'date_naissance', type: 'birthday', type_options: { widget: 'single_text', 'attr': {'class': 'datepicker'}}}
                - {property: 'telephone', type: 'tel'}
                - {property: 'email', type: 'email'}
                - {property: 'num_carte', type: 'number'}
                - {property: 'cniFile', type: 'file'}
            list:
                fields: ['id', 'votant', 'age', 'telephone', 'email', {property: 'cni_photo', label: 'CNI', type: 'image'}]
        Election:
            class: App\Entity\Election
            form:
                fields:
                    - 'nom'
                    - {property: 'debut_inscription', type: 'datetime', type_options: { widget: 'single_text', 'attr': {'class': 'datepicker'}}}
                    - {property: 'fin_inscription', type: 'datetime', type_options: { widget: 'single_text', 'attr': {'class': 'datepicker'}}}
                    - {property: 'debut_vote', type: 'datetime', type_options: { widget: 'single_text', 'attr': {'class': 'datepicker'}}}
                    - {property: 'fin_vote', type: 'datetime', type_options: { widget: 'single_text', 'attr': {'class': 'datepicker'}}}
            list:
                fields: ['id', 'nom', 'debut_inscription', 'fin_inscription', 'debut_vote', 'fin_vote']
        Role:
            class: App\Entity\Role
            form:
                fields: ['nom', 'description']
            list:
                fields: ['id', 'nom', 'description']
            disabled_actions: ['new']
        Utilisateur:
            form:
                fields:
                - 'username'
                - {property: 'email', type: 'email'}
                - {property: 'password', type: 'password', label: 'Mot de passe'}
                - 'role'
            class: App\Entity\User
            list:
                fields: ['id', 'username', 'email', 'role']
