security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        in_database:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 7200 # 2 hours in seconds
                path: /manager
    role_hierarchy:
        ROLE_ADMIN: REOLE_MANAGER
    access_control:
        - { path: ^/manager, roles: [ROLE_ADMIN, ROLE_MANAGER, ROLE_GESTION] }
