vich_uploader:
    db_driver: orm

    mappings:
        candidats:
            uri_prefix: '%candidat_images%'
            upload_destination: '%kernel.project_dir%/public%candidat_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        electteurs:
            uri_prefix: '%electeur_images%'
            upload_destination: '%kernel.project_dir%/public%electeur_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        documents:
            uri_prefix: '%election_documents%'
            upload_destination: '%kernel.project_dir%/public%election_documents%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
