vich_uploader:
    db_driver: orm

    mappings:
        candidats:
            uri_prefix: /images/candidats
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        electteurs:
            uri_prefix: /images/electeurs
            upload_destination: '%kernel.project_dir%/public/images/clients'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
