easy_admin:
    entities:
        Election:
            class: App\Entity\Election
            form:
                fields:
                    - 'nom'
                    - {property: 'debut_inscription', type: 'datetime', type_options: { widget: 'single_text'}}
                    - {property: 'fin_inscription', type: 'datetime', type_options: { widget: 'single_text'}}
                    - {property: 'debut_vote', type: 'datetime', type_options: { widget: 'single_text'}}
                    - {property: 'fin_vote', type: 'datetime', type_options: { widget: 'single_text'}}
            list:
                fields: ['id', 'nom', 'debut_inscription', 'fin_inscription', 'debut_vote', 'fin_vote']
            show:
                fields: ['nom', 'debut_inscription', 'fin_inscription', 'debut_vote', 'fin_vote']
