easy_admin:
    entities:
        Electeur:
            class: App\Entity\Electeur
            form:
                fields:
                    - 'nom'
                    - 'prenom'
                    - {property: 'date_naissance', type: 'date', type_options: { widget: 'single_text'}}
                    - {property: 'telephone', type: 'tel'}
                    - {property: 'email', type: 'email'}
                    - {property: 'num_carte', type: 'number'}
                    - {property: 'cniFile', type: 'vich_image'}
            list:
                fields:
                    - 'id'
                    - {property: 'valide', type: 'boolean', label: 'Active'}
                    - {property: 'votant', type: 'string'}
                    - {property: 'age', type: 'string'}
                    - 'telephone'
                    - 'email'
                    - {property: 'cni_photo', label: 'CNI', type: 'image', base_path: '%electeur_images%'}
                sort: 'valide'
            show:
                actions:
                    - {name: 'electeur_validation', type: 'route', icon: 'envelope', label: 'Valider', css_class: 'btn btn-success'}
                    - {name: '-edit'}
                    - {name: '-delete'}
                fields:
                    - {property: 'votant', type: 'string'}
                    - {property: 'age', type: 'string'}
                    - 'telephone'
                    - 'email'
                    - {property: 'num_carte', label: 'Num CNI', type: 'string'}
                    - {property: 'cni_photo', label: 'CNI', type: 'image', base_path: '%electeur_images%'}
                    - {property: 'num_electorale', label: 'Numero Electeur'}
