easy_admin:
    entities:
        Role:
            class: App\Entity\Role
            form:
                fields: ['nom', 'description']
            list:
                fields: ['id', 'nom', 'description']
            show:
                fields: ['nom', 'description']
            disabled_actions: ['new']
