easy_admin:
    entities:
        Utilisateur:
            class: App\Entity\User
            form:
                fields:
                - 'username'
                - {property: 'email', type: 'email'}
                - {property: 'password', type: 'password', label: 'Mot de passe'}
                - 'role'
            list:
                fields: ['id', 'username', 'email', 'role']
            show:
                fields: ['username', 'email', 'role']
